### ISSUE TITLE
Many bugs

### ISSUE THREAD

**Issue by Doctor-Venom** [redeye-framework/Redeye#6]
This is a nice project, but it is not practical to be used at its current state.

There are many bugs, for example:
1. if you create a new section in servers, and you delete the name, you will not be able to click on the textbox again to type a name.
2. thoughts and updates cannot be deleted (i get a white page with [Object Object] when i delete it).
3. I can't delete the server i created, the delete button on server page doesn't do anything.
4. after changing section name for servers, its not updated in the "Create New Server" window until you refresh the page.
and many others.

deployment was using docker.

**Comment by fsacer** [comment]
Agreed, definitely feels quite janky in the current state but I like the idea of having a tool for drawing like that.

**Comment by sisitrs2** [comment]
Yeah I guess you used the version from dockerhub, we used the latest version of neo4j which caused issues when they updated it.
Try using the stable version.
